In [1]:
import numpy as np

In [3]:
arr=np.array([3,2,6,8,5,8])
print(arr, type(arr))

[3 2 6 8 5 8] <class 'numpy.ndarray'>


In [6]:
# to check the time wheather np is faster than list or not
import time
size=10_000_000
listt= list(range(size))
start= time.time()
sq=[x**2 for x in listt]
end=time.time()
print(f'the exceution time for list is {end-start} ')

# now do it for numpy
arr=np.array(listt)

start= time.time()
sq_np=arr ** 2
end=time.time()
print(f'the exceution time for list is {end-start} ')

the exceution time for list is 2.5888664722442627 
the exceution time for list is 0.04126286506652832 


In [10]:
# For checking memory 
import sys
print(f'python list occupy {sys.getsizeof(listt) * len(listt)} bytes memory')
print(f'Numpy array occupy {arr.nbytes} bytes memory')

python list occupy 800000560000000 bytes memory
Numpy array occupy 80000000 bytes memory


# creating array from list and numpy properties

In [11]:
ar= np.array([1,3,5,67,6])
print(ar, type(ar), ar.shape, ar.dtype)

[ 1  3  5 67  6] <class 'numpy.ndarray'> (5,) int64


In [22]:
# 2d array or more dimension array
ar2= np.array([[1,2,4],[3,5,6],[7,8,9]])
print(ar2.shape, ar2)

(3, 3) [[1 2 4]
 [3 5 6]
 [7 8 9]]


In [32]:
#  Built in methods used in array
a= np.zeros((3,4), dtype='int64')
print(a, a.shape)

a1=np.arange(0,200, 10)     # from 0 to 200 bech me 10 10 ka gape
print(a1, a1.shape)

a2=np.full((3,4), 23)    # 3*4 matrix fill with 23
print(a2, a2.shape)

a3=np.linspace(2,200,6)    # evenly separate 6 values from 2 to 200
print(a3, a3.shape)

a4= np.eye((3), dtype='int64')   # identity matrix for 3*3
print(a4, a4.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190] (20,)
[[23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]] (3, 4)
[  2.   41.6  81.2 120.8 160.4 200. ] (6,)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)


In [41]:
#   properties of array
arr1= np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

#  type casting (changing from int to float)
flo=arr1.astype(np.float64)
print(flo, flo.dtype)

(3, 3)
9
2
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [6. 7. 8.]] float64


In [42]:
#  Reshaping
a=np.array([[1,2,4],[5,6,8,]])
print(a,a.shape)

[[1 2 4]
 [5 6 8]] (2, 3)


In [44]:
b=a.reshape((3,2))
print(b, b.shape)

[[1 2]
 [4 5]
 [6 8]] (3, 2)


In [47]:
# Indexing
a
print(a[0][1])

# fancy indexing
s=np.array([3,4,6,87,8,7])
idx=[1,3,4]
print(s[idx])

2
[ 4 87  8]


In [48]:
# boolean indexing
s
print(s[s>4])

[ 6 87  8  7]


In [50]:
# Slicing
s=np.array([3,4,6,87,8,7])
print(s[1::2])    # start from index 1 and jump 2 away and print and [start:end: step]

[ 4 87  7]


In [56]:
# view and copy difference in list and np array
# for python list     (ye copy banata he es leye eske serap copy me changes arahe he leken original same he)
num=[3,4,6,78,9,8]
copy= num[1:4]
print(copy)
copy[0]= 555
print(copy)
print(num)
 
# for numpy array   (ye serap view dekata he es leye es ke original me be changes ajate he )
# num=np.array([3,4,6,78,9,8])
# copy= num[1:4]
# print(copy)
# copy[0]= 555
# print(copy)
# print(num)

[4, 6, 78]
[555, 6, 78]
[3, 4, 6, 78, 9, 8]


In [58]:
# Different data types in numpy
a=np.array([1,2,4,4,5,3,2])
print(a, a.dtype)

a1=np.array(['hamza', {2,4,5,5}, 4.22])
print(a1, a1.dtype)

[1 2 4 4 5 3 2] int64
['hamza' {2, 4, 5} 4.22] object


In [62]:
# 2D Array and operations on it 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(a))
print(a)

45
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
sum_of_column=np.sum(a, axis=0)
print(sum_of_column)
sum_of_rows=np.sum(a, axis=1)
print(sum_of_rows)

[12 15 18]
[ 6 15 24]


In [66]:
print(a[2: ,1:])
print(a[1:2: , 0:2])    #doing slicing on above matrix

[[8 9]]
[[4 5]]


# Now practicing 3d array

In [68]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
print(a,a.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]] (2, 3, 3)


In [70]:
# indexing of 3d array
print(a[0,2,1])
print(a[1,1,2])

8
4


In [73]:
#slicing on 3d array
print(a[1,0:2,0:2])  #2nd layer ka row 0 and 1 and col 0 and 1
print(a[:,:,2])

# Data manupolation mean replacing one value with another
a[:,:,2]=88
print(a)

[[9 8]
 [6 5]]
[[3 6 9]
 [7 4 1]]
[[[ 1  2 88]
  [ 4  5 88]
  [ 7  8 88]]

 [[ 9  8 88]
  [ 6  5 88]
  [ 3  2 88]]]


In [79]:
#  Vectorization and Broadcasting
#vectorization
print('this is vectorization work')
v=np.array([1,2,3,4,5,6])
print(v**2)
print(v + 10)

#Broadcasting
print('this is broadcating work')
s=np.array([1,2,3,4,5])
s1=np.array([[1,2,3,4,5],[6,7,8,9,5]])
print(s+s1)

this is vectorization work
[ 1  4  9 16 25 36]
[11 12 13 14 15 16]
this is broadcating work
[[ 2  4  6  8 10]
 [ 7  9 11 13 10]]


In [80]:
# Vector normalization
vec=np.array([[1,2],[3,4]])
mean=np.mean(vec)
std=np.std(vec)
normalization=(vec-mean)/std
print(normalization)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [82]:
new_mean=np.mean(normalization)    # the mean of normalized vector is always zero 
new_std=np.std(normalization)      # while the std of normalized vector is 1 or close to 1
print(new_mean)
print(new_std)

0.0
1.0


In [89]:
#  Mathematical functions in numpy
a=np.array([1,2,4,5,6,7])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.argmax(a))
print(np.argmin(a))

4.166666666666667
4.5
2.1147629234082532
4.472222222222222
5
0


In [94]:
# Logs functions
a=np.array([1,2,4,5.9,6.4,7.3])
print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.exp(a))

# Rounding functions
print(np.round(a))
print(np.ceil(a))
print(np.floor(a))
print(np.trunc(a))

# Some extra functions
print(np.abs(a))
print(np.unique(a))
print(np.sort(a))

[0.         0.69314718 1.38629436 1.77495235 1.85629799 1.98787435]
[0.         0.30103    0.60205999 0.77085201 0.80617997 0.86332286]
[0.         1.         2.         2.56071495 2.67807191 2.86789646]
[   2.71828183    7.3890561    54.59815003  365.03746787  601.84503787
 1480.29992758]
[1. 2. 4. 6. 6. 7.]
[1. 2. 4. 6. 7. 8.]
[1. 2. 4. 5. 6. 7.]
[1. 2. 4. 5. 6. 7.]
[1.  2.  4.  5.9 6.4 7.3]
[1.  2.  4.  5.9 6.4 7.3]
[1.  2.  4.  5.9 6.4 7.3]
