In [1]:
import numpy as np

In [2]:
import time

In [5]:
size= 1000000
listt=list(range(size))
print(len(listt))

1000000


In [12]:
start=time.time()
square={x**2 for x in listt}
end= time.time()
print(f'The time for list exceution is {end-start} time')

nmp=np.array(listt)
start=time.time()
squa=nmp**2
end=time.time()
print(f'The time for numpy exceution is {end-start} time')

The time for list exceution is 0.5101876258850098 time
The time for numpy exceution is 0.005033969879150391 time


In [20]:
import sys     # list take more memory while numpy array get less memory
print(f'the size of list is {sys.getsizeof(listt)*len(listt)}')
print(f'the size of numpy array is {nmp.nbytes}')

the size of list is 8000056000000
the size of numpy array is 8000000


In [24]:
lis=[1,3,5,6,7,9,9.9]
nm=np.array(lis)
nm.shape
type(nm)

numpy.ndarray

In [26]:
nmp=np.array([[35,657,5667,4,33],[32,454,56,5,32]])
nmp.shape

(2, 5)

In [29]:
one=np.ones((3,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full((3,4), 400)

array([[400, 400, 400, 400],
       [400, 400, 400, 400],
       [400, 400, 400, 400]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.linspace(3,100, 6)

array([  3. ,  22.4,  41.8,  61.2,  80.6, 100. ])

In [37]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
one.size

15

In [39]:
one.shape

(3, 5)

In [40]:
one.dtype

dtype('float64')

In [41]:
one.ndim

2

In [42]:
a2=one.astype(np.int64)

In [46]:
a2.dtype

dtype('int64')

In [48]:
one.dtype

dtype('float64')

In [49]:
a2.shape

(3, 5)

In [50]:
a3=a2.reshape((5,3))

In [51]:
a3.shape

(5, 3)

In [52]:
a3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
a3[0]=100

In [58]:
a3[1][2]=500

In [59]:
a3

array([[100, 100, 100],
       [  1,   1, 500],
       [  1,   1,   1],
       [  1,   1,   1],
       [  1,   1,   1]])

In [60]:
one_d=a3.flatten()

In [61]:
one_d

array([100, 100, 100,   1,   1, 500,   1,   1,   1,   1,   1,   1,   1,
         1,   1])

In [62]:
one_d.shape

(15,)

In [68]:
idx=[0,3,5]
idx1=[0,2]
print(a3[idx1])
print(one_d[idx])

[[100 100 100]
 [  1   1   1]]
[100   1 500]


In [74]:
print(one_d[one_d>4])
print(a3[a3>0])

[100 100 100 500]
[100 100 100   1   1 500   1   1   1   1   1   1   1   1   1]


In [78]:
c1=np.array([2+3j])
c2=np.array([5-2j])
c3=c1+c2
print(c3)
c3.dtype

[7.+1.j]


dtype('complex128')

In [86]:
a={}
type(a)
# a1={3,}
# type(a1)
# a2=set()
# type(a2)

dict

In [97]:
d=nmp=np.array([[35,657,5667,4,33],[32,454,56,5,32]])
d.shape
d.ndim
# print(d[1,2])
print(np.mean(d))
print(np.sum(d,axis=1))   # sum of columns 
print(np.sum(d,axis=0))   # sum of rows 

697.5
[6396  579]
[  67 1111 5723    9   65]


In [98]:
d

array([[  35,  657, 5667,    4,   33],
       [  32,  454,   56,    5,   32]])

In [99]:
print(d[0:2, 1:3])

[[ 657 5667]
 [ 454   56]]


In [111]:
trd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])

In [112]:
trd.shape

(2, 3, 3)

In [113]:
trd

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [120]:
print(trd[1,0:3,0:3])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [123]:
print(trd[0,2,1])

8


In [127]:
trd[:,1, :]

array([[4, 5, 6],
       [6, 5, 4]])

In [132]:
a=[1,2,4,5]
a1=np.array([[2,3,4,5],[6,7,8,9]])
a1.shape
print(a+a1)     # Here broadcasting is occur where 1*4 is added with 2*4 matrix

[[ 3  5  8 10]
 [ 7  9 12 14]]


In [134]:
a3=np.array(a)
a4=4
print(a3+a4)

[5 6 8 9]


In [137]:
n=np.array([[2,3,4,5],[6,7,8,9]])
print(np.mean(n))
print(np.std(n))

5.5
2.29128784747792


In [139]:
print(a3**2)

[ 1  4 16 25]


In [140]:
a3.sum()

np.int64(12)

In [146]:
a3[0]=30
a3

array([30,  2,  4,  5])

In [145]:
print(a3.argmax())
print(a3.argmin())

0
1


In [149]:
print(np.log(a3))

[3.40119738 0.69314718 1.38629436 1.60943791]


In [151]:
# Rounding function in numpy
print(np.round(3.45))
print(np.ceil(3.45))
print(np.floor(3.45))
print(np.trunc(3.45))

3.0
4.0
3.0
3.0


In [157]:
u=np.array([3,5,-3,35,-7,8,5,3-8,-99,34])


In [159]:
print(np.sort(u))      #sort the values in ascending order
print(np.unique(u))    # give only unique values
print(np.abs(u))     # remove all negative signs and make it all positive

[-99  -7  -5  -3   3   5   5   8  34  35]
[-99  -7  -5  -3   3   5   8  34  35]
[ 3  5  3 35  7  8  5  5 99 34]
